---
title: "Data Mining Project"
author: "Amy Zheng"
date: "4/23/2017"
output: pdf_document
---

```{r}
rm(list=ls())
library(tidyverse)
library(devtools)


flights15 <- read.csv("flights2015.csv")
flights2015_mod = flights15[, -c(31:33, 35:40, 42:50, 52:53, 57:64)]
```

```{r}
#### ORIGIN airport delays ####
### filter our delayed flights ###
flights2015_mod_delay <- flights2015_mod[which(flights2015_mod$DEP_DEL15==1),]
### group by days ###
delays_by_days <- flights2015_mod_delay %>%
  group_by(FL_DATE, ORIGIN_AIRPORT_ID) %>%
  summarize(delays = n())
### get previous day ###
delays_by_days_2 <- mutate(delays_by_days, 
                           FL_DATE_2 = as.character(as.Date(FL_DATE)-1))
delays_by_days_3 <- left_join(delays_by_days_2, delays_by_days, 
                 by = c("FL_DATE_2" = "FL_DATE", 
                        "ORIGIN_AIRPORT_ID" = "ORIGIN_AIRPORT_ID"))
delays_by_days_3 <- mutate(delays_by_days_3, 
                           delays_2 = rowSums(cbind(delays.x, delays.y), na.rm=TRUE))
### add to data set ###
flights2015_mod_v1 <- left_join(flights2015_mod, delays_by_days_3, 
                 by = c("FL_DATE" = "FL_DATE", 
                        "ORIGIN_AIRPORT_ID" = "ORIGIN_AIRPORT_ID"))
flights2015_mod_v1 <- flights2015_mod_v1[, -c(38:39)]
```

```{r}
#### DESTINATION airport delays ####
### group by days ###
delays_by_des <- flights2015_mod_v1 %>%
  group_by(FL_DATE, DEST_AIRPORT_ID) %>%
  summarize(delays_des = n())
### get previous day ###
delays_by_des_2 <- mutate(delays_by_des, 
                           FL_DATE_2 = as.character(as.Date(FL_DATE)-1))
delays_by_des_3 <- left_join(delays_by_des_2, delays_by_des, 
                 by = c("FL_DATE_2" = "FL_DATE", 
                        "DEST_AIRPORT_ID" = "DEST_AIRPORT_ID"))
delays_by_des_3 <- mutate(delays_by_des_3, 
                           delays_des_2 = rowSums(cbind(delays_des.x, 
                                                        delays_des.y), 
                                                  na.rm=TRUE))
### add to data set ###
flights2015_mod_v2 <- left_join(flights2015_mod_v1, delays_by_des_3, 
                 by = c("FL_DATE" = "FL_DATE", 
                        "DEST_AIRPORT_ID" = "DEST_AIRPORT_ID"))
### get rid of useless variables ###
flights2015_mod_v2 <- flights2015_mod_v2[, -c(40:41)]
flights2015_mod_v2$DEP_DEL15 <- factor(flights2015_mod_v2$DEP_DEL15)
```



```{r}
#### ORIGIN airport delays ####
flights16_v <- read.csv("flights2016_visible.csv")
flights16_g <- read.csv("flights2016_guess.csv")
### filter our delayed flights ###
flights16_v_delay <- flights16_v[which(flights16_v$DEP_DEL15==1),]
### group by days ###
delays_by_days_16 <- flights16_v_delay %>%
  group_by(FL_DATE, ORIGIN_AIRPORT_ID) %>%
  summarize(delays = n())
### get previous day ###
delays_by_days_16_2 <- mutate(delays_by_days_16, 
                           FL_DATE_2 = as.character(as.Date(FL_DATE)-1))
delays_by_days_16_3 <- left_join(delays_by_days_16_2, delays_by_days_16, 
                 by = c("FL_DATE_2" = "FL_DATE", 
                        "ORIGIN_AIRPORT_ID" = "ORIGIN_AIRPORT_ID"))
delays_by_days_16_3 <- mutate(delays_by_days_16_3, 
                           delays_2 = rowSums(cbind(delays.x, delays.y), na.rm=TRUE))
### add to data set ###
flights16_v1 <- left_join(flights16_g, delays_by_days_16_3, 
                 by = c("FL_DATE" = "FL_DATE", 
                        "ORIGIN_AIRPORT_ID" = "ORIGIN_AIRPORT_ID"))
flights16_v1 <- flights16_v1[, -c(66:67)]
### add to 2016 visible data set ###
flights16_v_v1 <- left_join(flights16_v, delays_by_days_16_3, 
                 by = c("FL_DATE" = "FL_DATE", 
                        "ORIGIN_AIRPORT_ID" = "ORIGIN_AIRPORT_ID"))
flights16_v_v1 <- flights16_v_v1[, -c(66:67)]
```

```{r}
#### DESTINATION airport delays ####
### group by days ###
delays_by_des_16 <- flights16_v_delay %>%
  group_by(FL_DATE, DEST_AIRPORT_ID) %>%
  summarize(delays_des = n())
### get previous day ###
delays_by_des_16_2 <- mutate(delays_by_des_16, 
                           FL_DATE_2 = as.character(as.Date(FL_DATE)-1))
delays_by_des_16_3 <- left_join(delays_by_des_16_2, delays_by_des_16, 
                 by = c("FL_DATE_2" = "FL_DATE", 
                        "DEST_AIRPORT_ID" = "DEST_AIRPORT_ID"))
delays_by_des_16_3 <- mutate(delays_by_des_16_3, 
                           delays_des_2 = rowSums(cbind(delays_des.x,
                                                    delays_des.y), 
                                              na.rm=TRUE))
### add to data set ###
flights16_v2 <- left_join(flights16_v1, delays_by_des_16_3, 
                 by = c("FL_DATE" = "FL_DATE", 
                        "DEST_AIRPORT_ID" = "DEST_AIRPORT_ID"))
flights16_v2 <- flights16_v2[, -c(68:69)]

### add to 2016 visible data set ###
flights16_v_v2 <- left_join(flights16_v_v1, delays_by_des_16_3, 
                 by = c("FL_DATE" = "FL_DATE", 
                        "DEST_AIRPORT_ID" = "DEST_AIRPORT_ID"))
flights16_v_v2 <- flights16_v_v2[, -c(68:69)]
```

```{r}
holidays <- c('2015-01-01', '2015-01-19', '2015-02-14', '2015-02-16',
              '2015-05-25', '2015-07-04', '2015-09-07',
              '2015-10-12','2015-11-11','2015-11-26', '2015-12-25')
holidayDates <- as.Date(holidays)
DaysToHoliday <- function(month, day){ 
  # Input a month and day from the flightsDB
    # Get our year.
    year <- 2015
    currDate <- as.Date(paste(year,month,day,sep = '-')) 
    # Create a DATE object we can use to calculate the time difference
    numDays <- as.numeric(min(abs(currDate-holidayDates))) 
    # Now find the minimum difference between the date and our holidays
    return(numDays)                                        
    # We can vectorize this to automatically find the minimum closest
    # holiday by subtracting all holidays at once
}
# Get all of the dates through unique Month/Day combinations
datesOfYear <- unique(flights2015_mod_v2[,3:4]) 
# Apply our function in a vectorized manner via one of R's many "apply" functions (in this case mapply)
# to each unique date and save 
datesOfYear$HDAYS <- mapply(DaysToHoliday, datesOfYear$MONTH, datesOfYear$DAY_OF_MONTH) 
InputDays <- function(month,day){
    finalDays <- datesOfYear$HDAYS[datesOfYear$MONTH == month & datesOfYear$DAY_OF_MONTH == day] # Find which row to get
    return(finalDays)
}
flights2015_mod_v2$HDAYS <- mapply(InputDays, 
                                   flights2015_mod_v2$MONTH, 
                                   flights2015_mod_v2$DAY_OF_MONTH)
```

```{r}
holidays_16 <- c('2016-01-01', '2016-01-18', '2016-02-14', '2016-02-15',
              '2016-05-30', '2016-07-04', '2016-09-05',
              '2016-10-10','2016-11-11','2016-11-24', '2016-12-25')
holidayDates_16 <- as.Date(holidays_16)
DaysToHoliday_16 <- function(month, day){ 
    year <- 2016
    currDate <- as.Date(paste(year,month,day,sep = '-')) 
    numDays <- as.numeric(min(abs(currDate-holidayDates_16))) 
    return(numDays)                                        
}
datesOfYear_16 <- unique(flights16_v2[,3:4])
datesOfYear_16$HDAYS <- mapply(DaysToHoliday_16, datesOfYear_16$MONTH,
                            datesOfYear_16$DAY_OF_MONTH) 
InputDays_16 <- function(month,day){
    finalDays <- datesOfYear_16$HDAYS[datesOfYear_16$MONTH == month & datesOfYear_16$DAY_OF_MONTH == day] # Find which row to get
    return(finalDays)
}
flights16_v2$HDAYS <- mapply(InputDays_16, 
                             flights16_v2$MONTH, 
                             flights16_v2$DAY_OF_MONTH)

### add to 2016 visible data set ###
datesOfYear_16_v <- unique(flights16_v_v2[,3:4])
datesOfYear_16_v$HDAYS <- mapply(DaysToHoliday_16, datesOfYear_16_v$MONTH,
                            datesOfYear_16_v$DAY_OF_MONTH) 
InputDays_v_16 <- function(month,day){
    finalDays <- datesOfYear_16_v$HDAYS[datesOfYear_16_v$MONTH == month & datesOfYear_16_v$DAY_OF_MONTH == day] # Find which row to get
    return(finalDays)
}
flights16_v_v2$HDAYS <- mapply(InputDays_v_16, 
                             flights16_v_v2$MONTH, 
                             flights16_v_v2$DAY_OF_MONTH)
```



```{r}
# weekday vs. weekend
flights2015_mod_v2$WEEKEND <- ifelse(flights2015_mod_v2$DAY_OF_WEEK>5, 1,0)
flights16_v2$WEEKEND <- ifelse(flights16_v2$DAY_OF_WEEK>5, 1,0)
flights16_v_v2$WEEKEND <- ifelse(flights16_v_v2$DAY_OF_WEEK>5, 1,0)
# season 
Season <- function(month){
  if (month > 2 & month < 6 ){
    return(1)
  }
  else if (month > 5 & month < 9){
    return(2)
  }
  else if (month > 8 & month < 12){
    return(3)
   }
  else{
    return(4)
  }
}
flights2015_mod_v2$SEASON =  mapply(Season, 
                             flights2015_mod_v2$MONTH)
flights16_v2$SEASON =  mapply(Season, 
                             flights16_v2$MONTH)
flights16_v_v2$SEASON =  mapply(Season, 
                             flights16_v_v2$MONTH)

```


```{r}
# Carrier name
# "AA","American Airlines Inc."
# "B6","JetBlue Airways"
# "DL","Delta Air Lines Inc."
# "EV","ExpressJet Airlines Inc."
# "MQ","Envoy Air"
# "OO","SkyWest Airlines Inc."
# "UA","United Air Lines Inc."
# "US","US Airways Inc."
# "WN","Southwest Airlines Co."
```

```{r}
# Deal with imbalanced data 
library(ROSE)
flights2015_over <- ovun.sample(DEP_DEL15 ~ ., data = flights2015_mod_v2, method = "both", N = 60000)$data
flights2015_over <- flights2015_over[, -c(1,6, 10,11)]



#Make test set
set.seed(4)
idx = sample(1:nrow(flights2015_over),20000)
testing = flights2015_over[idx,]
training = flights2015_over[-idx,]
```


```{r}
# Deal with imbalanced data 
library(ROSE)
flights2015_over <- ovun.sample(DEP_DEL15 ~ ., data = flights2015_mod_v2, method = "both", N = 60000)$data
flights2015_over <- flights2015_over[, -c(1,6, 10,11)]



#Make test set
set.seed(4)
idx = sample(1:nrow(flights2015_over),20000)
testing = flights2015_over[idx,]
training = flights2015_over[-idx,]
```

```{r}
# Logistic Regression 

# Logistic Lasso 
```



```{r}
library(randomForest)
# Problem of TAIL_NUM and FL_NUM categories levels > 53
forest = randomForest(DEP_DEL15 ~., data = training, ntree = 500, na.action = na.pass)

yhat_test = predict(forest,newdata = testing)
yhat_train = predict(forest, newdata = training)

test_err = mean(yhat_test != testing$DEP_DEL15)
train_err = mean(yhat_train != training$DEP_DEL15)
# oob_err = rev(forest$mse)[1]




importance(forest)
varImpPlot(forest)

# Deal with missing values

summary(flights2015_over)
```

```{r}
# Additive Model

```